"""
Create a program that will play the “cows and bulls” game with the user. The game works like this:

Randomly generate a 4-digit number. Ask the user to guess a 4-digit number. For every digit that the user guessed correctly in the correct place, they have a “cow”. For every digit the user guessed correctly in the wrong place is a “bull.” Every time the user makes a guess, tell them how many “cows” and “bulls” they have. Once the user guesses the correct number, the game is over. Keep track of the number of guesses the user makes throughout the game and tell the user at the end.

Say the number generated by the computer is 1038. An example interaction could look like this:

  Welcome to the Cows and Bulls Game!
  Enter a number: 
  >>> 1234
  2 cows, 0 bulls
  >>> 1256
  1 cow, 1 bull
  ...
  
Until the user guesses the number.
"""
import random
import string

rand_nums = random.sample(string.digits, 4)
cows, bulls, count = 0, 0, 0

print("Welcome to the Cows and Bulls Game!")
while True:
	temp_cows, temp_bulls = cows, bulls
	cows, bulls = 0, 0
	
	user_nums = input("Please enter 4-digit number:\n")
	user_nums = list(user_nums)
	if user_nums[0] == rand_nums[0]:
		cows += 1
	if user_nums[1] == rand_nums[1]:
		cows += 1
	if user_nums[2] == rand_nums[2]:
		cows += 1
	if user_nums[3] == rand_nums[3]:
		cows += 1
	
	if temp_cows + temp_bulls > cows and count > 0:
		bulls = temp_cows + temp_bulls - cows
	count += 1
	print("Cows:", cows)
	print("Bulls:", bulls)
	print("\n\n")
	
	if cows == 4:
		print("Congratulations, you won, the random number is", "".join(rand_nums))
		print("You tried,", count, "times.")
		break
			































